homepage:
    path:             /
    defaults:         { _controller: AppBundle:Default:index }
    methods:          [GET]

convocantes:
    path:             /convocantes.json
    defaults:         { _controller: AppBundle:Default:convocantes }
    methods:          [GET]
